apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: pve
spec:
  headers:
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 63072000
    customResponseHeaders:
      x-powered-by: ""
    frameDeny: true
    customFrameOptionsValue: "SAMEORIGIN"
    contentTypeNosniff: true
    referrerPolicy: "strict-origin-when-cross-origin"
    permissionsPolicy: "camera=(), microphone=(), geolocation=()"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: pve
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pve.hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: pve
spec:
  tls:
    secretName: wildcard-hyvel-certificate-secret
    domains:
      - main: pve.hyvel.eu
  entryPoints:
    - websecure
  routes:
    - match: Host(`pve.hyvel.eu`) && PathRegexp(`^.*\.(woff2?|ttf|eot|otf)$`)
      middlewares:
        - name: security-headers
          namespace: pve
        - name: compress
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: pve-svc
          port: 8006
          scheme: https
          serversTransport: pve-transport
    - match: Host(`pve.hyvel.eu`)
      middlewares:
        - name: anubis
          namespace: traefik
        - name: security-headers
          namespace: pve
        - name: compress
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: pve-svc
          port: 8006
          scheme: https
          serversTransport: pve-transport


---

apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pve-transport
  namespace: pve

spec:
  insecureSkipVerify: true
