apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: ts
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ts.ho.hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: ts
spec:
  tls:
    secretName: wildcard-ho-hyvel-certificate-secret
    domains:
      - main: ts.ho.hyvel.eu
  entryPoints:
    - websecure
  routes:
    - match: Host(`ts.ho.hyvel.eu`)
      middlewares:
        - name: compress
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: ts
          port: 7540
