apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: immich
spec:
  headers:
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 63072000
    customResponseHeaders:
      x-powered-by: ""
    frameDeny: true
    customFrameOptionsValue: "SAMEORIGIN"
    contentTypeNosniff: true
    referrerPolicy: "strict-origin-when-cross-origin"
    permissionsPolicy: "camera=(), microphone=(), geolocation=()"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: immich
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`imch.hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: immich
spec:
  tls:
    secretName: wildcard-hyvel-certificate-secret
    domains:
      - main: imch.hyvel.eu
  entryPoints:
    - websecure
  routes:
    - match: Host(`imch.hyvel.eu`)
      middlewares:
        - name: anubis
          namespace: traefik
        - name: security-headers
          namespace: immich
        - name: compress
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: immich
          port: 7571