apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: hyvel
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      root /data/current/public;
      index index.html index.htm;
      
      include mime.types;
      types {
        application/manifest+json webmanifest;
      }

      location / {
        try_files $uri $uri/ =404;
      }
    }