apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: hyvel
spec:
  headers:
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 63072000
    customResponseHeaders:
      server: ""
    frameDeny: true
    customFrameOptionsValue: "SAMEORIGIN"
    contentTypeNosniff: true
    referrerPolicy: "strict-origin-when-cross-origin"
    permissionsPolicy: "camera=(), microphone=(), geolocation=()"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: hyvel
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: app
          port: 7581

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: hyvel
spec:
  tls:
    secretName: wildcard-hyvel-certificate-secret
    domains:
      - main: hyvel.eu
  entryPoints:
    - websecure
  routes:
    - match: Host(`hyvel.eu`) && PathRegexp(`^.*\.(woff2?|ttf|eot|otf)$`)
      middlewares:
        - name: security-headers
          namespace: hyvel
        - name: compress
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: app
          port: 7581

    - match: Host(`hyvel.eu`)
      middlewares:
        - name: anubis
          namespace: traefik
        - name: security-headers
          namespace: hyvel
        - name: compress
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: app
          port: 7581