apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: vw
spec:
  headers:
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 63072000
    customResponseHeaders:
      server: ""

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: vw
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`vault.hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: vw
spec:
  tls:
    secretName: wildcard-hyvel-certificate-secret
    domains:
      - main: vault.hyvel.eu
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.hyvel.eu`) && PathRegexp(`^.*\.(woff2?|ttf|eot|otf)$`)
      middlewares:
        - name: security-headers
          namespace: vw
        - name: compress
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: vaultwarden
          port: 7561

    - match: Host(`vault.hyvel.eu`)
      middlewares:
        - name: anubis
          namespace: traefik
        - name: security-headers
          namespace: vw
        - name: compress
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: vaultwarden
          port: 7561