apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: anubis
spec:
  headers:
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 63072000
    customResponseHeaders:
      server: ""
    frameDeny: true
    customFrameOptionsValue: "SAMEORIGIN"
    contentTypeNosniff: true
    referrerPolicy: "strict-origin-when-cross-origin"
    permissionsPolicy: "camera=(), microphone=(), geolocation=()"

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: anubis
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prt.hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: anubis
spec:
  tls:
    secretName: wildcard-hyvel-certificate-secret
    domains:
      - main: hyvel.eu
        sans:
          - "prt.hyvel.eu"
  entryPoints:
    - websecure
  routes:
    - match: Host(`prt.hyvel.eu`)
      middlewares:
        - name: security-headers
          namespace: anubis
        - name: compress
          namespace: traefik
        - name: cache
          namespace: traefik
      kind: Rule
      services:
        - kind: Service
          name: anubis
          port: 7580
